[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["usercatalog"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "usercatalog"
  org = "shiroorg"
  version = "1.0.1"

